### ISSUE TITLE
custom_nodes\ComfyUI-FAI-Node\requirement.txt , not   requirements.txt

### ISSUE THREAD

**Issue by isamu2025** [alanhuang67/ComfyUI-FAI-Node#3]
custom_nodes\ComfyUI-FAI-Node>..\..\..\python_embeded\python.exe -s -m pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

haha ;)

**Comment by alanhuang67** [comment]
thanks~ already update~
